language: go
go:
- 1.16.x
before_install:
- go get github.com/mattn/goveralls
install: true
script:
- go test -coverprofile=cover.out -covermode=atomic -race -v ./...
- goveralls -coverprofile=cover.out -service=travis-ci
