language: go
go:
  - 1.13.x
  - master
env:
  - GO111MODULE=on
before_install:
  - go get github.com/mattn/goveralls
install: true
script:
  - GO111MODULE=on go test -coverprofile=cover.out -covermode=atomic -race -v ./...
  - goveralls -coverprofile=cover.out -service=travis-ci
